### PR TITLE
Add RTRs 

### PR DESCRIPTION
**Pull request by mrdenman-nuclear**
This PR adds RSS feeds for Research and Test Reactors. 

No review is required, if the tests build then the feature will be deployed.

### CODE REVIEW

**Review by jordagaman — APPROVED** [review]
YOLO

**Comment by mrdenman-nuclear** [comment]
You know, sometimes you edit things directly on GitHub and you miss something. This time it was updating the exported variable list.

**Comment by mrdenman-nuclear** [comment]
> YOLO

Move fast and break things

**Comment by mrdenman-nuclear** [comment]
Green light on package down.

**Pull request merged**
